// <auto-generated />
using System;
using ApexGoalTrackerAPI.DataObjects;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApexGoalTrackerAPI.Migrations
{
    [DbContext(typeof(ApexContext))]
    partial class ApexContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApexGoalTrackerAPI.DataObjects.CurrentStats", b =>
                {
                    b.Property<string>("ApexID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("RankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RankSore")
                        .HasColumnType("int");

                    b.Property<string>("banner")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApexID");

                    b.ToTable("currentStats");
                });

            modelBuilder.Entity("ApexGoalTrackerAPI.DataObjects.User", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApexID")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("UserName");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ApexGoalTrackerAPI.DataObjects.UserGoal", b =>
                {
                    b.Property<string>("ApexID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RankScore")
                        .HasColumnType("int");

                    b.HasKey("ApexID");

                    b.ToTable("userGoals");
                });

            modelBuilder.Entity("ApexGoalTrackerAPI.DataObjects.CurrentStats", b =>
                {
                    b.HasOne("ApexGoalTrackerAPI.DataObjects.User", "User")
                        .WithMany()
                        .HasForeignKey("ApexID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApexGoalTrackerAPI.DataObjects.UserGoal", b =>
                {
                    b.HasOne("ApexGoalTrackerAPI.DataObjects.User", "User")
                        .WithMany()
                        .HasForeignKey("ApexID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
